name: Spell Checker

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: "aas,aaS,ba,bund,compliancy,firt,ist,keypair,ligh,Manuel,Manual,ro,ser,synopsys,theses,zuser,lief,EDE"
          skip: "*.json,*.yml,*.apk,*.ipa,*.svg,*.txt"
